name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup python version
      uses: actions/setup-python@v1
      with: 
        python-version: 3.8

    - name: Install dependencies
      run: make install

    - name: Run format
      run: make format

    - name: Run lint
      run: make lint

    - name: Run test
      run: make test 
    
    - name: Run build
      run: make build

    - name: Run docker
      run: make run



