name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup python 3.10
      uses: actions/setup-python@v1
      with: 
        python-version: 3.10

    - name: Install dependencies
      run: make install

    - name: Run format
      run: make format

    - name: Run lint
      run: make lint
